name=Soldered BMM350 Geomagnetic Sensor
version=1.0.0
author=Soldered
maintainer=Soldered <soldered@soldered.com>
sentence=Library for the Soldered BMM350 Geomagnetic Sensor breakout board
paragraph=Library for the Soldered BMM350 Geomagnetic Sensor breakout board, providing basic functionalities for communicating with the board via I2C
category=Sensors
url=https://www.soldered.com/
repository=https://github.com/SolderedElectronics/Soldered-BMM350-Arduino-Library
architectures=*
includes=BMM350-SOLDERED.h
